Made it A TON BETTER

diff --git a/cmdinstall b/cmdinstall
--- a/cmdinstall
+++ b/cmdinstall
@@ -1,117 +1,145 @@
 #!/bin/bash
-function warning(){
-    echo -ne "\033[41;1m WARNING: " >&2
-    echo -e "$@ \033[01;0m" >&2
+#######################################
+#
+#	Tomoyo After Patch
+#		Zenity Version
+#
+#	Version:
+#		git
+#
+#	Author:
+#	    Swiss <swiss@veryoblivio.us>
+#
+#
+#	This doesn't use Bashv4....
+#		Stupid mac.
+#    This script is meant to install 
+#	Tomoyo After with Zenity
+#######################################
+
+##Zenity Functions (to make everything faster)
+#non critical error
+function error() {
+     echo -ne "\033[41;1m WARNING: " >&2
+     echo -e "$1 \033[01;0m" >&2
+}
+function yesno() {
+    read -p "$1? [y/n] " answer
+    case $answer in
+	[Yy]*)echo "0"; return 0;;
+	[Nn]*)echo "1"; return 1;;
+	*)echo "$answer could not be understood. Interpreting as 'no'"; return 1;;
+    esac
+}
+function upperthis(){
+    echo $@ | tr [:lower:] [:upper:]
 }
 function lowerthis(){
-   echo $@ | tr [:upper:] [:lower:]
+    echo $@ | tr [:upper:] [:lower:]
 }
-which rlvm > /dev/null
-if [ "$?" = "1" ];
-   then
-   warning "RLVM was not found installed on this system. Please install it 
-before attempting to install the patch, as the patch won't work without
-it.\nRLVM can be found at http://www.elliotglaysher.org/rlvm/"
-fi
-echo -ne "Do you already have Tomoyo After installed?"
-read installed
-installed=$(lowerthis $installed)
-if [[ "$installed" == no ]] | [[ "$installed" == n ]];
-   then
-   echo "Please specify the location of 'Tomoyo After ~It's a Wonderful Life~'"
-   read installdisc
-   if [ -f "$installdisc/Seen.txt" ]; then
-      echo "Please specify the directory Tomoyo After should be installed into
-\n This creates a new directory of 'Tomoyo After' under whatever directory
-you specify"
-   else
-      warning "Your install location seems to be incorrect or you have a bad disc."
-      exit 1
-   fi
-   read installloc
-   if [ -z "$installloc" ];
-      then 
-      warning "No location given."
-      exit 1
-   fi
-   echo "Tomoyo After will now be installed. This may take a while. Press OK to start the installtion."
-   running=1
-   mkdir "$installloc/Tomoyo After/";
-   chmod +w "$installloc/Tomoyo After";
-   echo "Installing, may take some time"
-   for i in `echo bgm dat dt00.dll Gameexe.ini g00 koe gan manual mov sys wav Seen.txt Tomoyo.ico`; 
-      do cp -r "$installdisc/$i" "$installloc/Tomoyo After/" &
-   done
-# No progress bar for cmd install
-#   while [ $running -eq 1 ];
-#      do
-#      chmod +w -R "$installloc/Tomoyo After";
-#      some=$(sed -e "s/ .*$//" <<< `du -s "$installloc/Tomoyo After"`)
-#      let " progress = 100 * some / 2146664"
-#      echo -n "$progress"
-#      if [ "$progress" -eq 100 ]
-#	 then running=0
-#      fi
-#      sleep 1
-#   done
-   preinstall=1
-   else
-	preinstall=0
-fi;
+function crit() {
+     echo -ne "\033[41;1m CRITICAL ERROR: " >&2
+     echo -e "$1 \033[01;0m" >&2
+     exit 1
+}
+function seldir() {
+    read -e -p "$1 >" DESTINATION
+    while [ ! -d "$DESTINATION" ]
+    do
+	error "That destionation is not a valid directory!"
+	read -e -p ">" DESTINATION
+    done
+    echo $DESTINATION
+}
+function cancelled() {
+    echo -ne "\033[41;1m Installation Cancelled! \033[01;0m" >&2
+    exit 1
+}
+##Zenity Versions
+#Yes no question
+function zenq() {
+    zenity --question --text="$1"
+    return $?
+}
+#info dialog
+function zeninfo() {
+    zenity --info --text="$1"
+}
+#Directory selection
+function zendir() {
+    zenity --file-selection --directory --title="$1" $2
+}
+#critical error
+function zencrit() {
+    zenity --error --text="$1"
+    exit 1
+}
+function zencancel() {
+    zenity --error --text="Install Cancelled"
+    exit 1
+}
+
+which rlvm >&2 2>/dev/null || crit "RLVM was not found installed on this system. Please install it before attempting to install the patch, as the patch won't work without it.\nRLVM can be found at http://www.elliotglaysher.org/rlvm/"
+preinstall=$(yesno "Do you already have Tomoyo After installed?")
+
+#Install from Disc
+if [[ $preinstall -eq 0 ]]; then
+    echo -e "Please specify the location of the disk labeled 'Tomoyo After ~It's a Wonderful Life~'"
+    installdisc=$(seldir "Tomoyo After Install Disc")
+    [ -f "$installdisc/Seen.txt" ] || [[ -f "$installdisc/SEEN.TXT" ]] || crit "Your install location seems to be incorrect or you have a bad disc."
+    echo -e "Please specify the directory Tomoyo After should be installed into \n This creates a new directory of 'Tomoyo After' under whatever directory you specify" "--filename=~/";
+    installloc=$(seldir "Destination Directory") || cancelled
+    echo -e "Tomoyo After will now be installed. This may take a while. Press OK to start the installtion." || cancelled
+    mkdir "$installloc/Tomoyo After/";
+	chmod +w "$installloc/Tomoyo After"
+	for i in `echo bgm dat dt00.dll Gameexe.ini g00 koe gan manual mov sys wav Seen.txt Tomoyo.ico`
+	do
+	    cp -r "$installdisc/$i" "$installloc/Tomoyo After/" &
+	done
+    running=true
+    while [[ $running == true ]]
+    do
+	chmod +w -R "$installloc/Tomoyo After";
+	some=$(sed -e "s/ .*$//" << `du -s "$installloc/Tomoyo After"`)
+	let " progress = 100 * some / 2146664"
+	printf "\r $progress % copied"
+	if [[ "$progress" -eq 100 ]]
+	    then running=false
+	fi
+    done
+    tomodir="$installloc/Tomoyo After"
 #End Install Disc
-#Getting the installation directoy
-if [ "$preinstall" -eq 1 ]; then
-   tomodir="$installloc/Tomoyo After"
 else
-   echo -e "Please specify the location of your Tomoyo After installation
-(If installed through wine it should be ~/.wine/drive_c/KEY/Tomoyo After/"
-   read tomodir
-   #probably a cleaner way to do this ignoring capitilization
-   if [ -e "$tomodir/Gameexe.ini" ]; then
-      mv "$tomodir/Gameexe.ini" "$tomodir/GAMEEXE.INI"
-   else 
-      if [ ! -e "$tomodir/GAMEEXE.INI" ]; then
-#Failed check
-	 warning "This installer cannot find Gameexe.ini or GAMEEXE.INI inside
-	 $tomodir. Please doublecheck that you specified the correct
-	 directory."
-	 exit 1
-      fi
-   fi
+    echo -e "Please specify the location of your Tomoyo After installation \n (If installed through wine it should be ~/.wine/drive_c/KEY/Tomoyo After/"  || cancelled
+    tomodir=$(seldir "Installed Directory")
+    #probably a cleaner way to do this ignoring capitilization, but oh well
+    [ -e "$tomodir/Gameexe.ini" ] &&	mv "$tomodir/Gameexe.ini" "$tomodir/GAMEEXE.INI"
+    [ -e "$tomodir/GAMEEXE.INI" ] || crit "This installer cannot find Gameexe.ini or GAMEEXE.INI inside $tomodir.\n Please doublecheck that you specified the correct directory."
 fi
 chmod +rw -R "$tomodir"
-#End of Installation Directory finding, now to copy the patch
+#Done with their directory
+
+##End of Installation Directory finding, now to copy the patch
+
 #Font first
-echo -e "A font chosen by the designers of the patch will now be placed on your
-system. Please choose a directory for it to be placed into. \n If no directory
-is specified the font will be placed in the same directory as Tomoyo After"
-read fontdir
-if [ -z "$fontdir" ];
-   then
-   fontdir=$tomodir
-fi
+echo -e "A font chosen by the designers of the patch will now be placed on your system. Please choose a directory for it to be placed into."
+fontdir=$(seldir "Font Directory" "--filename=~/.rlvm/" || cancelled)
 cp msgothic.ttc "$fontdir"
 
 
-#Final time asking
-echo -e "Do you want to continue installing the patch? \n (Last chance to back out)"
-read backout
-if [ -z "$backout" ] || [[ ${backout,,} == n. ]]
-   then exit 1;
-fi
-##WILL NEED EDITING FOR THE REAL FILES
-##ASSUMING A CONSTANT NAMING SCHEME. CAN BE BROKEN
+#Final time asking before overwriting
+yesno "Do you want to continue installing the patch? (Last chance to back out)" || cancelled
 if [ -e "$tomodir/Seen.txt" ]; then
-   m="bgm dat gan koe mov sys wav Seen.txt"
-   for i in `echo $m`; do
-      if [ -e "$tomodir/$i" ]; then
-	 j=$(echo $i | tr '[:lower:]' '[:upper:]' )
-	 mv "$tomodir/$i" "$tomodir/$j"
-      fi
-   done
-   chmod +rw -R "$tomodir"
-   m="SEEN* rlBabel.dll 1.3.5.4.map GAMEEXE.INI G00 MOV"
-   for i in `echo $m`;
+    m="bgm dat gan koe mov sys wav Seen.txt"
+    for i in `echo $m`; do
+	if [ -e "$tomodir/$i" ]; then
+	    j=$(upperthis $i)
+	    mv "$tomodir/$i" "$tomodir/$j"
+	fi
+    done
+    chmod +rw -R "$tomodir"
+   
+   for i in "SEEN* rlBabel.dll 1.3.5.4.map GAMEEXE.INI G00 MOV"
       do cp $i "$tomodir" -r
    done
 fi
@@ -119,24 +147,15 @@ fi
 #Nice desktop installer
 ##TO DO make it purty
 if [ -e ~/Desktop ];
-   then
-   echo "Do you want a desktop launcher to be installed to run Tomoyo After?"
-   read desktopinstaller
-   if [ -z "$desktopinstaller" ]
-      then
-      #Won't work for mac
-      echo -e '#!/bin/bash' " \nrlvm --font \042"$fontdir/msgothic.ttc"\042 \042"$tomodir"\042 " > ~/Desktop/TomoyoAfter
-      chmod +x ~/Desktop/TomoyoAfter
-      echo "A shortcut to run Tomoyo After has been placed on your desktop. If
-you wish to run Tomoyo After via the command line please execute: \n rlvm
-      --font \042 $fontdir/msgothic.ttc\042 \042 $tomodir \042 "
-   fi
+then
+    yesno "Do you want a desktop launcher to be installed to run Tomoyo After?" && (
+    echo -e '#!/bin/bash' " \nrlvm --font \042"$fontdir/msgothic.ttc"\042 \042"$tomodir"\042 " > ~/Desktop/TomoyoAfter
+    chmod +x ~/Desktop/TomoyoAfter
+    echo -e "A shortcut to run Tomoyo After has been placed on your desktop. If you wish to run Tomoyo After via the command line please execute: \n rlvm --font \042 $fontdir/msgothic.ttc\042 \042 $tomodir \042 "
+    )
 fi
 
 
-echo "Thank you for using Doki\'s Tomoyo After installer!"
-#EOF
+echo -e "Thank you for using Doki\'s Tomoyo After installer!"
+#EOF, clean exit
 exit 0
-
-
-# vim: set sw=3 tw=80  #
